// The share card is generated by hand (scripts/make-social.mjs needs macOS
// system fonts, so it cannot run on a CI runner) and the result is committed.
// A hand-run step that nobody reruns is a claim that goes stale: the card said
// draft-imran-systems-and-arguments-03 while the document said -05, and the
// card is the first thing most readers ever see.
//
// make-social.mjs stamps the identifier it used. This compares that stamp
// against the identifier in the built page.
import { readFileSync, existsSync } from 'node:fs'

const page = 'dist/index.html'
const stamp = 'scripts/og-cover.id'

if (!existsSync(page)) {
  console.log('\nsocial card\n  no dist/index.html, skipping\n')
  process.exit(0)
}

const ident = (readFileSync(page, 'utf8').match(/draft-imran-systems-and-arguments-\d{2}/) || [])[0]
const carded = existsSync(stamp) ? readFileSync(stamp, 'utf8').trim() : null

console.log('\nsocial card')
console.log(`  document   ${ident ?? 'not found'}`)
console.log(`  share card ${carded ?? 'never stamped'}`)

if (!carded) {
  console.error('\nsocial check FAILED: no stamp. Run `npm run social` to regenerate the card.\n')
  process.exit(1)
}
if (carded !== ident) {
  console.error(`\nsocial check FAILED: the card says ${carded}, the document says ${ident}.`)
  console.error('Run `npm run build` then `npm run social`, and commit public/og-cover.*\n')
  process.exit(1)
}
console.log('  ok  the card and the document agree\n')
