// The strict CSP has no script-src, so default-src 'none' governs, and that
// blocks <script type="application/ld+json"> too. Those blocks are data rather
// than code, but CSP does not make that distinction.
//
// Rather than weaken the policy or drop the structured data, hash every block
// and emit a per-path script-src into _headers. Policy stays strict, the data
// validates, the console stays clean.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const walk = (d, o = []) => { for (const e of readdirSync(d, { withFileTypes: true })) {
  const p = join(d, e.name); e.isDirectory() ? walk(p, o) : o.push(p) } return o }

const BASE = "default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'; upgrade-insecure-requests"
const rules = []
let blocks = 0

for (const f of walk('dist').filter((x) => x.endsWith('.html'))) {
  const html = readFileSync(f, 'utf8')
  const hashes = []
  for (const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    hashes.push(`'sha256-${createHash('sha256').update(m[1], 'utf8').digest('base64')}'`)
    blocks++
  }
  // Every HTML page gets exactly one policy. Pages without JSON-LD get the base
  // with no script-src at all, so default-src 'none' governs and nothing runs.
  let route = '/' + f.replace(/^dist\//, '').replace(/index\.html$/, '')
  route = route.replace(/\/{2,}/g, '/')
  const policy = hashes.length
    ? `${BASE}; script-src ${[...new Set(hashes)].join(' ')}`
    : `${BASE}; script-src 'none'`
  rules.push(`${route}\n  Content-Security-Policy: ${policy}\n`)
}

const headers = readFileSync('dist/_headers', 'utf8')
writeFileSync('dist/_headers',
  headers + '\n# Generated by scripts/csp-hashes.mjs. Per-path script-src for the\n' +
  '# JSON-LD blocks, so the policy stays strict without dropping structured data.\n\n' +
  rules.join('\n'))
console.log(`\ncsp hashes\n  ld+json blocks hashed  ${blocks}\n  per-path rules written ${rules.length}\n`)
