// The CSP names the JSON-LD hashes and one third-party host, and that
// blocks <script type="application/ld+json"> too. Those blocks are data rather
// than code, but CSP does not make that distinction.
//
// Rather than weaken the policy or drop the structured data, hash every block
// and emit a per-path script-src into _headers. Policy stays strict, the data
// validates, the console stays clean.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const walk = (d, o = []) => { for (const e of readdirSync(d, { withFileTypes: true })) {
  const p = join(d, e.name); e.isDirectory() ? walk(p, o) : o.push(p) } return o }

// Cloudflare Web Analytics, allowed by name on 2026-09-03. The beacon was being
// injected into every response and refused by this policy, so the feature was on
// and collecting nothing while the page still paid for the request. The owner
// chose to make it work rather than turn it off. Erratum 7.25.
//
// script-src lets it execute. connect-src lets it report, and the host it
// reports to is NOT the host it loads from: the script comes from the CDN and
// posts to /cdn-cgi/rum on this origin. Pinning connect-src to the CDN, which is
// what the first version of this did, left the script running and every report
// refused, so the feature stayed broken and erratum 7.25 said it was fixed.
// Verified in a browser rather than reasoned about. Erratum 7.42.
//
// Everything else stays exactly as strict as it was: no 'unsafe-inline' for
// script, no wildcard, and img-src, form-action, base-uri and frame-ancestors
// are untouched.
const BEACON_HOST = 'https://static.cloudflareinsights.com'
const BASE = "default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'; upgrade-insecure-requests" +
  `; connect-src 'self'`
/*
 * Cloudflare Pages enforces a hard limit of 100 rules in _headers and silently
 * skips the rest. One rule per page was fine at 44 pages. The tools catalogue
 * took the site to 185, which would have dropped the policy from roughly half
 * of them in production with nothing but a build-log warning to say so.
 *
 * So pages are grouped by the policy they need. Only the 26 that carry JSON-LD
 * need a hash of their own; every other page gets a byte-identical policy, and
 * a directory whose pages all want that same policy collapses to one wildcard.
 * The policy each page receives is unchanged. There are simply fewer lines
 * saying it.
 *
 * A wildcard may never overlap a page needing a different policy: _headers rules
 * are additive and two CSP headers intersect, so an overlap would silently
 * break the JSON-LD it was written to allow. collapse() only emits a wildcard
 * for a directory where every page underneath agrees.
 */
const pages = []
let blocks = 0

for (const f of walk('dist').filter((x) => x.endsWith('.html'))) {
  const html = readFileSync(f, 'utf8')
  const hashes = []
  for (const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    hashes.push(`'sha256-${createHash('sha256').update(m[1], 'utf8').digest('base64')}'`)
    blocks++
  }
  let route = '/' + f.replace(/^dist\//, '').replace(/index\.html$/, '')
  route = route.replace(/\/{2,}/g, '/')
  // The beacon lands on every HTML response, including pages with no JSON-LD, so
  // it belongs in script-src on all of them rather than only where a hash exists.
  const sources = [...new Set(hashes), BEACON_HOST]
  pages.push({ route, policy: `${BASE}; script-src ${sources.join(' ')}` })
}

// The policy shared by the most pages is the one worth collapsing. It is always
// the no-JSON-LD policy, but it is computed rather than assumed.
const tally = new Map()
for (const p of pages) tally.set(p.policy, (tally.get(p.policy) || 0) + 1)
const common = [...tally.entries()].sort((a, b) => b[1] - a[1])[0][0]

const dirOf = (route) => {
  const parts = route.split('/').filter(Boolean)
  return parts.length ? `/${parts[0]}/` : '/'
}

// A directory collapses only when every page in it wants the common policy and
// there is more than one of them.
const byDir = new Map()
for (const p of pages) {
  const d = dirOf(p.route)
  if (!byDir.has(d)) byDir.set(d, [])
  byDir.get(d).push(p)
}
const collapsed = new Set()
const rules = []
for (const [dir, group] of byDir) {
  if (dir === '/') continue
  if (group.length < 2) continue
  if (!group.every((p) => p.policy === common)) continue
  rules.push(`${dir}*\n  Content-Security-Policy: ${common}\n`)
  for (const p of group) collapsed.add(p.route)
}
for (const p of pages) {
  if (collapsed.has(p.route)) continue
  rules.push(`${p.route}\n  Content-Security-Policy: ${p.policy}\n`)
}

const headers = readFileSync('dist/_headers', 'utf8')
writeFileSync('dist/_headers',
  headers + '\n# Generated by scripts/csp-hashes.mjs. Per-path script-src for the\n' +
  '# JSON-LD blocks, so the policy stays strict without dropping structured data.\n\n' +
  rules.join('\n'))
/*
 * The limit that made this necessary, asserted rather than trusted. Cloudflare
 * skips rules past 100 and reports it as a warning in a build log nobody reads,
 * which is how a page can serve with no CSP and every check still pass.
 */
const LIMIT = 100
const total = readFileSync('dist/_headers', 'utf8')
  .split('\n').filter((l) => /^\//.test(l)).length

console.log(`\ncsp hashes\n  ld+json blocks hashed  ${blocks}`)
console.log(`  pages                  ${pages.length}`)
console.log(`  wildcard rules         ${collapsed.size} pages collapsed into ${rules.length - (pages.length - collapsed.size)}`)
console.log(`  csp rules written      ${rules.length}`)
console.log(`  _headers rules total   ${total} / ${LIMIT}`)
if (total > LIMIT) {
  console.error(`\nFAILED: _headers has ${total} rules and Cloudflare Pages enforces ${LIMIT}.`)
  console.error('Everything past the limit is skipped silently, so those pages would serve with no CSP.\n')
  process.exit(1)
}
console.log('')
