/*
 * Fetches every tool's own homepage: liveness, where it redirects to, and what
 * the vendor says about itself.
 *
 * This exists because the catalogue's descriptions came from three strangers'
 * curation, and a curated list is a snapshot of somebody's opinion on the day
 * they wrote it. A product's own page is the primary source for what it claims
 * to do, and it is the only place the "most advertised use case" actually
 * lives. It is also the only way to find out that a tool is gone.
 *
 * Output is src/data/tools-live.json, committed. Nothing here reaches the
 * network at build time.
 *
 * Usage: node scripts/fetch-tools.mjs [--concurrency 8] [--only slug,slug]
 */

import { readFileSync, writeFileSync } from 'node:fs'

const CONCURRENCY = Number(process.argv[process.argv.indexOf('--concurrency') + 1]) || 8
const ONLY = process.argv.includes('--only')
  ? new Set(process.argv[process.argv.indexOf('--only') + 1].split(','))
  : null
const TIMEOUT_MS = 15_000

// Identifies the crawler and points at the page explaining why it called. A
// bot that will not say who it is has no business asking for anybody's HTML.
const UA = 'Mozilla/5.0 (compatible; imran-site-toolcheck/1.0; +https://mosthofaimran.com/tools/)'

const catalogue = JSON.parse(readFileSync('src/data/tools.json', 'utf8'))
const tools = catalogue.tools.filter((t) => !ONLY || ONLY.has(t.slug))

function decode (s) {
  return s
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#0?39;|&apos;|&#x27;/gi, "'")
    .replace(/&nbsp;/g, ' ').replace(/&mdash;/g, ', ').replace(/&ndash;/g, ', ')
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/\s+/g, ' ')
    .trim()
}

function meta (html, names) {
  for (const n of names) {
    const re = new RegExp(
      `<meta[^>]+(?:name|property)=["']${n}["'][^>]*content=["']([^"']*)["']`, 'i')
    const m = html.match(re) || html.match(new RegExp(
      `<meta[^>]+content=["']([^"']*)["'][^>]*(?:name|property)=["']${n}["']`, 'i'))
    if (m && m[1].trim()) return decode(m[1])
  }
  return ''
}

async function probe (tool) {
  const started = Date.now()
  const ctl = new AbortController()
  const timer = setTimeout(() => ctl.abort(), TIMEOUT_MS)
  try {
    const r = await fetch(tool.url, {
      redirect: 'follow',
      signal: ctl.signal,
      headers: { 'user-agent': UA, accept: 'text/html,application/xhtml+xml' },
    })
    const finalUrl = r.url || tool.url
    const ct = r.headers.get('content-type') || ''
    let html = ''
    if (r.ok && /html/i.test(ct)) html = (await r.text()).slice(0, 400_000)

    const h1m = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)
    return {
      slug: tool.slug,
      status: r.status,
      ok: r.ok,
      finalUrl,
      redirected: finalUrl.replace(/\/$/, '') !== tool.url.replace(/\/$/, ''),
      title: html ? decode((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i) || [, ''])[1]) : '',
      description: meta(html, ['description', 'og:description', 'twitter:description']),
      ogTitle: meta(html, ['og:title', 'twitter:title']),
      h1: h1m ? decode(h1m[1].replace(/<[^>]+>/g, ' ')).slice(0, 200) : '',
      ms: Date.now() - started,
    }
  } catch (e) {
    return {
      slug: tool.slug,
      status: 0,
      ok: false,
      finalUrl: tool.url,
      redirected: false,
      title: '', description: '', ogTitle: '', h1: '',
      error: e.name === 'AbortError' ? 'timeout' : String(e.cause?.code || e.message).slice(0, 60),
      ms: Date.now() - started,
    }
  } finally {
    clearTimeout(timer)
  }
}

const results = []
let done = 0
const queue = [...tools]
await Promise.all(Array.from({ length: CONCURRENCY }, async () => {
  for (;;) {
    const t = queue.shift()
    if (!t) return
    results.push(await probe(t))
    done++
    if (done % 50 === 0) console.log(`  ${done}/${tools.length}`)
  }
}))

results.sort((a, b) => a.slug.localeCompare(b.slug))
writeFileSync('src/data/tools-live.json', JSON.stringify({
  checked: new Date().toISOString().slice(0, 10),
  note: 'Generated by scripts/fetch-tools.mjs. Each tool\'s own homepage, as it answered on the date above.',
  results,
}, null, 1) + '\n')

const dead = results.filter((r) => !r.ok)
const noDesc = results.filter((r) => r.ok && !r.description && !r.h1 && !r.ogTitle)
console.log(`\n  ${results.length} probed`)
console.log(`  ${results.length - dead.length} answered, ${dead.length} did not`)
console.log(`  ${results.filter((r) => r.redirected).length} redirected somewhere else`)
console.log(`  ${noDesc.length} answered with nothing to describe them by\n`)
const byStatus = {}
for (const r of results) byStatus[r.error || r.status] = (byStatus[r.error || r.status] || 0) + 1
for (const [k, n] of Object.entries(byStatus).sort((a, b) => b[1] - a[1])) console.log(`  ${String(k).padEnd(24)} ${n}`)
